# yaml-language-server: $schema=https://raw.githubusercontent.com/riscv/riscv-unified-db/main/spec/schemas/config_schema.json

# Copyright (c) 2026, 10xEngineers, Harvey Mudd College and Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1

# UDB Architecture Configuration for the WardRV
---
$schema: config_schema.json#
kind: architecture configuration
type: fully configured
name: WardRV
description: WardRV
implemented_extensions:
  - { name: I,     version: "= 2.1" }
  - { name: Zicsr, version: "= 2.0" }
  - { name: Sm,    version: "= 1.13.0" }

params:
  # Sm params
  MXLEN: 32
  PRECISE_SYNCHRONOUS_EXCEPTIONS: false
  TRAP_ON_ECALL_FROM_M: false
  TRAP_ON_EBREAK: false
  MARCHID_IMPLEMENTED: false
 #ARCH_ID_VALUE: 0x1
  MIMPID_IMPLEMENTED: false
 #IMP_ID_VALUE: 0x0
  VENDOR_ID_BANK: 0x0
  VENDOR_ID_OFFSET: 0x0
  MISALIGNED_LDST: false
  MISALIGNED_LDST_EXCEPTION_PRIORITY: low
 #MISALIGNED_MAX_ATOMICITY_GRANULE_SIZE: 4096
 #MISALIGNED_SPLIT_STRATEGY: sequential_bytes
  TRAP_ON_ILLEGAL_WLRL: false
  TRAP_ON_UNIMPLEMENTED_INSTRUCTION: false
  TRAP_ON_RESERVED_INSTRUCTION: false
  TRAP_ON_UNIMPLEMENTED_CSR: false
  REPORT_VA_IN_MTVAL_ON_BREAKPOINT: false
  REPORT_VA_IN_MTVAL_ON_LOAD_MISALIGNED: false
  REPORT_VA_IN_MTVAL_ON_STORE_AMO_MISALIGNED: false
  REPORT_VA_IN_MTVAL_ON_INSTRUCTION_MISALIGNED: false
  REPORT_VA_IN_MTVAL_ON_LOAD_ACCESS_FAULT: false
  REPORT_VA_IN_MTVAL_ON_STORE_AMO_ACCESS_FAULT: false
  REPORT_VA_IN_MTVAL_ON_INSTRUCTION_ACCESS_FAULT: false
  REPORT_ENCODING_IN_MTVAL_ON_ILLEGAL_INSTRUCTION: false
  MTVAL_WIDTH: 32
  CONFIG_PTR_ADDRESS: 0
  PMA_GRANULARITY: 3
  PHYS_ADDR_WIDTH: 32
  M_MODE_ENDIANNESS: little
  MISA_CSR_IMPLEMENTED: false
  MTVEC_ACCESS: rw
  MTVEC_MODES: [0, 1]
  MTVEC_BASE_ALIGNMENT_DIRECT: 4
  MTVEC_BASE_ALIGNMENT_VECTORED: 4
  MTVEC_ILLEGAL_WRITE_BEHAVIOR: retain
  COUNTINHIBIT_EN:
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ]
  NUM_PMP_ENTRIES: 0
  HPM_COUNTER_EN:
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ]
  MCOUNTENABLE_EN:
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ]
