#!/usr/bin/bash
#set -euo pipefail

# === Paramètres de l'environnement ===
ROOT="$(pwd)/riscv-compliance-ws"
RISCV="${ROOT}/opt/riscv"             # installation prefix for Spike (no sudo)
SRC="${ROOT}/src"
WORK="${ROOT}/riscof_rv32i"           # RISCOF execution folder
OUT="${ROOT}/out/signatures/rv32i"    # signature collection
JOBS=4

mkdir -p "${RISCV}" "${SRC}" "${WORK}" "${OUT}"

echo "[1/5] Installing required Ubuntu packages (sudo) ..."
sudo apt-get update -y
# 1) Precompiled RISC-V GCC Toolchain (bare-metal 64-bit, used for 32-bit via symlinks)
sudo apt-get install -y gcc-riscv64-unknown-elf
# 2) Spike dependencies + general tools
sudo apt-get install -y \
  device-tree-compiler libboost-all-dev \
  autoconf automake autotools-dev curl python3 python3-pip python3-tomli \
  gawk build-essential bison flex texinfo gperf libtool patchutils bc \
  zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev libslirp-dev \
  libmpc-dev libmpfr-dev libgmp-dev pkg-config

# Add to PATH (current session) for potential local bins
export PATH="${RISCV}/bin:${HOME}/.local/bin:/opt/bin:${PATH}"

# Create symbolic links for riscv32 (the plugin expects this prefix)
mkdir -p "${RISCV}/bin"
for tool in gcc objdump objcopy; do
  ln -sf "$(command -v riscv64-unknown-elf-${tool})" "${RISCV}/bin/riscv32-unknown-elf-${tool}"
done

echo "[2/5] Installing Spike (riscv-isa-sim) ..."
if ! command -v spike >/dev/null 2>&1; then
  cd "${SRC}"
  if [ ! -d riscv-isa-sim ]; then
    git clone https://github.com/riscv-software-src/riscv-isa-sim.git
  fi
  mkdir -p riscv-isa-sim/build
  cd riscv-isa-sim/build
  ../configure --prefix="${RISCV}"
  make -j"${JOBS}"
  make install
else
  echo "  -> Spike already present: $(spike --version 2>/dev/null || echo OK)"
fi
# (Procedure compliant with Spike docs/README)                                      # refs
# Spike ISS + dtc/boost dependencies                                                # [3](https://deepwiki.com/riscv-non-isa/riscv-arch-test/2.2-reference-models-%28spike-and-sail%29)[4](https://github.com/lowRISC/riscv-compliance/blob/master/doc/README.adoc)

echo "[3/5] Installing RISCOF (arch-tests framework) ..."
PIP_ARGS="--user"
if python3 -c 'import sys; sys.exit(0 if sys.prefix != sys.base_prefix else 1)' 2>/dev/null; then
  PIP_ARGS=""
fi
python3 -m pip install ${PIP_ARGS} --upgrade pip
python3 -m pip install ${PIP_ARGS} "git+https://github.com/riscv/riscof.git"
# (Installation method recommended by the arch-test/riscof repository)              # [5](https://www.yorku.ca/professor/drsmith/2024/07/28/getting-started-with-risc-v-spike-simulator/)

echo "[4/5] Fetching riscv-arch-test suite ..."
cd "${SRC}"
if [ ! -d riscv-arch-test ]; then
  git clone -b main https://github.com/riscv-non-isa/riscv-arch-test.git
fi
SUITE_DIR="${SRC}/riscv-arch-test/riscv-test-suite/rv32i_m"
ENV_DIR="${SRC}/riscv-arch-test/riscv-test-suite/env"
PLUGIN_DIR="${SRC}/riscv-arch-test/riscof-plugins/rv32/spike_simple"

# Prepare a minimal config.ini (DUT=Spike, Reference=Spike) to run the suite
mkdir -p "${WORK}"
cat > "${WORK}/config.ini" <<EOF
[RISCOF]
ReferencePlugin=spike_simple
ReferencePluginPath=${PLUGIN_DIR}
DUTPlugin=spike_simple
DUTPluginPath=${PLUGIN_DIR}

[spike_simple]
pluginpath=${PLUGIN_DIR}
ispec=${PLUGIN_DIR}/spike_simple_isa.yaml
pspec=${PLUGIN_DIR}/spike_simple_platform.yaml
EOF

echo "[5/5] Running RV32I_M suite (RISCOF + Spike) and extracting signatures ..."
cd "${WORK}"
# Run tests for the RV32I_M suite with the provided environment
riscof --verbose info run --config ./config.ini --suite "${SUITE_DIR}" --env "${ENV_DIR}"
# (Command compliant with RISCOF + arch-tests documentation)
# [5](https://www.yorku.ca/professor/drsmith/2024/07/28/getting-started-with-risc-v-spike-simulator/)
# [6](http://riscv.epcc.ed.ac.uk/documentation/how-to/install-spike/)

# Collect signature files generated by the campaign
mkdir -p "${OUT}"
cd "${WORK}/riscof_work"
find . -type f \
  \( -name "*.signature" -o -name "*.signature.output" -o -iname "*signature*.txt" -o -name "DUT.signature" \) \
  -exec cp --parents {} "${OUT}/" \; || true

echo
echo "======================================="
echo "Finished."
echo " - GCC Toolchain (apt): riscv64-unknown-elf-gcc (usable with -march=rv32i -mabi=ilp32)"
echo " - Working directory: ${WORK}"
echo " - Arch-tests directory: ${SRC}/riscv-arch-test"
echo " - Signatures copied to: ${OUT}"
echo "   (Full artifacts available under ${WORK}/riscof_work)"
echo "======================================="
